package dc.visao.folhapagamento.movimento;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.folhapagamento.movimento.FechamentoFormController;

public class FechamentoFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private TextField tfProximoFechamento;

	@AutoGenerated
	private TextField tfFechamentoAtual;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private FechamentoFormController controller;

	public FechamentoFormView(final FechamentoFormController controller) {
		this.controller = controller;

		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}

	public TextField getTfFechamentoAtual() {
		return tfFechamentoAtual;
	}

	public void setTfFechamentoAtual(TextField tfFechamentoAtual) {
		this.tfFechamentoAtual = tfFechamentoAtual;
	}

	public TextField getTfProximoFechamento() {
		return tfProximoFechamento;
	}

	public void setTfProximoFechamento(TextField tfProximoFechamento) {
		this.tfProximoFechamento = tfProximoFechamento;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_2.addComponent(gridLayout_1);

		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		// gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setRows(20);
		gridLayout_1.setColumns(2);

		// tfFechamentoAtual
		tfFechamentoAtual = new TextField();
		tfFechamentoAtual.setCaption("Fechamento atual:");
		tfFechamentoAtual.setImmediate(false);
		tfFechamentoAtual.setWidth("175px");
		tfFechamentoAtual.setHeight("-1px");
		tfFechamentoAtual.setSizeFull();
		tfFechamentoAtual.setNullRepresentation("");
		gridLayout_1.addComponent(tfFechamentoAtual, 0, 1);

		// tfProximoFechamento
		tfProximoFechamento = new TextField();
		tfProximoFechamento.setCaption("Proximo fechamento:");
		tfProximoFechamento.setImmediate(false);
		tfProximoFechamento.setWidth("175px");
		tfProximoFechamento.setHeight("-1px");
		tfProximoFechamento.setSizeFull();
		tfProximoFechamento.setNullRepresentation("");
		gridLayout_1.addComponent(tfProximoFechamento, 1, 1);

		return gridLayout_1;
	}

}