package dc.visao.geral.pessoal;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.geral.pessoal.NivelFormacaoFormController;
import dc.visao.framework.util.ComponentUtil;

public class NivelFormacaoFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField tfNome;

	@AutoGenerated
	private TextArea tfDescricao;

	@AutoGenerated
	private TextField tfGrauInstrucaoCaged;

	@AutoGenerated
	private TextField tfGrauInstrucaoSefip;

	@AutoGenerated
	private TextField tfGrauInstrucaoRais;

	private NivelFormacaoFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public NivelFormacaoFormView(NivelFormacaoFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.controller = controller;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	public TextArea getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(TextArea tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public TextField getTfGrauInstrucaoCaged() {
		return tfGrauInstrucaoCaged;
	}

	public void setTfGrauInstrucaoCaged(TextField tfGrauInstrucaoCaged) {
		this.tfGrauInstrucaoCaged = tfGrauInstrucaoCaged;
	}

	public TextField getTfGrauInstrucaoSefip() {
		return tfGrauInstrucaoSefip;
	}

	public void setTfGrauInstrucaoSefip(TextField tfGrauInstrucaoSefip) {
		this.tfGrauInstrucaoSefip = tfGrauInstrucaoSefip;
	}

	public TextField getTfGrauInstrucaoRais() {
		return tfGrauInstrucaoRais;
	}

	public void setTfGrauInstrucaoRais(TextField tfGrauInstrucaoRais) {
		this.tfGrauInstrucaoRais = tfGrauInstrucaoRais;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);

		return mainLayout;
	}

	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(4);
		fields.setColumns(4);

		// tfNome
		tfNome = ComponentUtil.buildTextField("Nome");
		fields.addComponent(tfNome, 0, 0, 1, 0);

		// tfDescricao
		tfDescricao = ComponentUtil.buildTextArea("Descrição");
		fields.addComponent(tfDescricao, 0, 2, 2,2);

		// tfGrauInstrucaoCaged
		tfGrauInstrucaoCaged = ComponentUtil.buildTextField("Grau de instrução CAGED");
		tfGrauInstrucaoCaged.setImmediate(false);
		fields.addComponent(tfGrauInstrucaoCaged, 0, 1);

		// tfGrauInstrucaoSefip
		tfGrauInstrucaoSefip = ComponentUtil.buildTextField("Grau de instrução SEFIP");
		tfGrauInstrucaoSefip.setImmediate(false);
		fields.addComponent(tfGrauInstrucaoSefip, 1, 1);

		// tfGrauInstrucaoRais
		tfGrauInstrucaoRais = ComponentUtil.buildTextField("Grau de instrução RAIS");
		tfGrauInstrucaoRais.setImmediate(false);
		fields.addComponent(tfGrauInstrucaoRais, 2, 1);

		return fields;
	}

}