package dc.visao.comercial;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.comercial.NotaFiscalTipoFormController;
import dc.visao.framework.util.ComponentUtil;

public class NotaFiscalTipoFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	NotaFiscalTipoFormController controller;

	@AutoGenerated
	private GridLayout fields;

	private TextField txtSerie;

	private TextField txtNome, txtDescricao;

	private TextField  txtUltimoNumero;

	public NotaFiscalTipoFormView(NotaFiscalTipoFormController controller) {
		this.controller = controller;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		fields = buildFields();
		mainLayout.addComponent(fields);

		return mainLayout;

	}

	@AutoGenerated
	private GridLayout buildFields() {
		// common part: create layout
		fields = new GridLayout(6, 6);
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);

		txtNome = ComponentUtil.buildTextField("Nome");
		fields.addComponent(txtNome, 0, 0);

		txtDescricao = ComponentUtil.buildTextField("Descrição");
		fields.addComponent(txtDescricao, 1, 0, 4, 0);

		txtSerie = ComponentUtil.buildTextField("Série");
		txtSerie.setMaxLength(3);
		fields.addComponent(txtSerie, 0, 1);

		txtUltimoNumero = ComponentUtil.buildNumericField("Último Número");
		fields.addComponent(txtUltimoNumero, 1, 1);

		return fields;

	}

	public TextField getTxtSerie() {
		return txtSerie;
	}

	public void setTxtSerie(TextField txtSerie) {
		this.txtSerie = txtSerie;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextField getTxtDescricao() {
		return txtDescricao;
	}

	public void setTxtDescricao(TextField txtDescricao) {
		this.txtDescricao = txtDescricao;
	}

	public TextField getTxtUltimoNumero() {
		return txtUltimoNumero;
	}

	public void setTxtUltimoNumero(TextField txtUltimoNumero) {
		this.txtUltimoNumero = txtUltimoNumero;
	}

}