package dc.visao.ordemservico;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

import dc.visao.framework.util.ComponentUtil;

public class InformacoesGeraisFormView {

	@AutoGenerated
	private GridLayout fieldsLine, fieldsLine1, fieldsLine2, fieldsLine3, fieldsLine4;
		
	@AutoGenerated
	private PopupDateField dtPopupDateField, dtEntrada, dtEfetiv, dtDataHoraEntrega;
	
	@AutoGenerated
	private ComboBox cbComboBox, cbStatus, cbSituacaoServico, cbAtendente,cbCliente, cbPlacaVeiculo, cbPagamentoLembrete;
	
	@AutoGenerated
	private TextField txNumComanda, txNumOs, txMotorizacao;
	
	@AutoGenerated
	private TextArea txAreaDefeitoApresentado;
	
	@AutoGenerated
	private CheckBox chDataHoraEntrega;
	
	public Component infoGeraisLine1() {
		
		fieldsLine1 = new GridLayout(6,1);
		cbStatus = new ComboBox();
		cbSituacaoServico = new ComboBox();
		fieldsLine1.setImmediate(false);
		fieldsLine1.setWidth("100.0%");
		fieldsLine1.setHeight("-1px");
		fieldsLine1.setMargin(true);
		fieldsLine1.setSpacing(true);
		fieldsLine1.setColumnExpandRatio(0, 0.05f);
		fieldsLine1.setColumnExpandRatio(1, 0.05f);
		fieldsLine1.setColumnExpandRatio(2, 0.05f);
		fieldsLine1.setColumnExpandRatio(3, 0.05f);
		fieldsLine1.setColumnExpandRatio(4, 0.05f);
		fieldsLine1.setColumnExpandRatio(5, 0.05f);
		
		fieldsLine1.addComponent(txNumOs = ComponentUtil.buildTextField("Nr. OS"), 0, 0);
        fieldsLine1.addComponent(dtEntrada = ComponentUtil.buildPopupDateField("Data Entrada"), 1, 0);
        fieldsLine1.addComponent(dtEfetiv = ComponentUtil.buildPopupDateField("Data Efetivação"), 2, 0);
        
        fieldsLine1.addComponent(txNumComanda = ComponentUtil.buildTextField("Nr. Comanda"), 3, 0);
		fieldsLine1.addComponent(cbStatus = ComponentUtil.buildComboBox("Status"), 4, 0);
		fieldsLine1.addComponent(cbSituacaoServico = ComponentUtil.buildComboBox("Situação Serviço"), 5, 0);
		
		return fieldsLine1;
	}

	public Component infoGeraisLine2() {

		fieldsLine2 = new GridLayout(6,1);
		cbAtendente = new ComboBox();
		cbCliente = new ComboBox();
		fieldsLine2.setImmediate(false);
		fieldsLine2.setWidth("100.0%");
		fieldsLine2.setHeight("-1px");
		fieldsLine2.setMargin(true);
		fieldsLine2.setSpacing(true);		
		fieldsLine2.setColumnExpandRatio(0, 0.05f);
		fieldsLine2.setColumnExpandRatio(1, 0.05f);
		fieldsLine2.setColumnExpandRatio(2, 0.01f);
		fieldsLine2.setColumnExpandRatio(3, 0.05f);
		fieldsLine2.setColumnExpandRatio(4, 0.05f);
		fieldsLine2.setColumnExpandRatio(5, 0.05f);

		fieldsLine2.addComponent(cbAtendente = ComponentUtil.buildComboBox("Atendente"), 0, 0);
        fieldsLine2.addComponent(cbCliente = ComponentUtil.buildComboBox("Cliente"), 1, 0);
		
		return fieldsLine2;
	}
	
	public Component infoGeraisLine3() {

		fieldsLine3 = new GridLayout(6,1);
		cbPlacaVeiculo = new ComboBox();
		fieldsLine3.setImmediate(false);
		fieldsLine3.setWidth("100.0%");
		fieldsLine3.setHeight("-1px");
		fieldsLine3.setMargin(true);
		fieldsLine3.setSpacing(true);
		fieldsLine3.setColumnExpandRatio(0, 0.05f);
		fieldsLine3.setColumnExpandRatio(1, 0.05f);
		fieldsLine3.setColumnExpandRatio(2, 0.05f);
		fieldsLine3.setColumnExpandRatio(3, 0.05f);
		fieldsLine3.setColumnExpandRatio(4, 0.05f);
		fieldsLine3.setColumnExpandRatio(5, 0.05f);

		fieldsLine3.addComponent(cbPlacaVeiculo = ComponentUtil.buildComboBox("Placa Veículo"), 0, 0);
		fieldsLine3.addComponent(txMotorizacao = ComponentUtil.buildTextField("Motorização"), 1, 0);
		
		return fieldsLine3;
	}
	
	public Component infoGeraisLine4() {

		fieldsLine4 = new GridLayout(6,3);
		fieldsLine = new GridLayout(1,1);
		cbPagamentoLembrete = new ComboBox();
		fieldsLine4.setImmediate(false);
		fieldsLine4.setWidth("100.0%");
		fieldsLine4.setHeight("-1px");
		fieldsLine4.setMargin(true);
		fieldsLine4.setSpacing(true);
		fieldsLine4.setColumnExpandRatio(0, 0.05f);
		fieldsLine4.setColumnExpandRatio(1, 0.05f);
		fieldsLine4.setRowExpandRatio(1, 0.5f);
		fieldsLine4.setColumnExpandRatio(2, 0.05f);
		fieldsLine4.setColumnExpandRatio(3, 0.05f);
		fieldsLine4.setColumnExpandRatio(4, 0.05f);
		fieldsLine4.setColumnExpandRatio(5, 0.05f);

		txAreaDefeitoApresentado = ComponentUtil.buildTextArea("teste de variação");
		txAreaDefeitoApresentado.setWidth("400px");
		txAreaDefeitoApresentado.setHeight("200px");
				
		fieldsLine4.addComponent(txAreaDefeitoApresentado, 0, 0);
		fieldsLine.addComponent(dtDataHoraEntrega = ComponentUtil.buildPopupDateField("Data e Hora da Entrada"));
		fieldsLine.addComponent(chDataHoraEntrega = ComponentUtil.buildCheckBox("Verificar data e hora da entrega!"));
		
		cbPagamentoLembrete = ComponentUtil.buildComboBox("Forma de pagamento para lembrete");
		cbPagamentoLembrete.setWidth("200px");
				
		fieldsLine.addComponent(cbPagamentoLembrete);
		fieldsLine4.addComponent(fieldsLine, 1, 0);
		
		return fieldsLine4;
	}
	
}
