package dc.visao.ordemservico;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

import dc.visao.framework.util.ComponentUtil;

public class ObservacaoFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private TextArea tfObservacaoOS;

	@AutoGenerated
	private TextArea tfObservacaoLocal;
	
	@AutoGenerated
	private Button btnPesquisar;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

//	private LaudoTecnicoFormController controller;

//	public LaudoTecnicoFormView(final LaudoTecnicoFormController controller) {
//		this.controller = controller;
//
//		buildMainLayout();
//		setCompositionRoot(this.mainLayout);
//	}

	public ObservacaoFormView() {
		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_2.addComponent(gridLayout_1);

		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setRows(20);
		gridLayout_1.setColumns(3);

		// tfObservacaoOS
		tfObservacaoOS = new TextArea();
		tfObservacaoOS = ComponentUtil.buildTextArea("Observação laudo técnico");
		tfObservacaoOS.setNullRepresentation("");
		tfObservacaoOS.setImmediate(false);
		tfObservacaoOS.setWidth("100%");
		tfObservacaoOS.setHeight("400px");
		gridLayout_1.addComponent(tfObservacaoOS, 0, 1);
		
		// tfObservacaoLaudoFerramentas
		tfObservacaoLocal = new TextArea();
		tfObservacaoLocal.setCaption("Esta ficando no local");
		tfObservacaoLocal.setNullRepresentation("");
		tfObservacaoLocal.setImmediate(false);
		tfObservacaoLocal.setWidth("100%");
		tfObservacaoLocal.setHeight("200px");
		gridLayout_1.addComponent(tfObservacaoLocal, 0, 2);

		return gridLayout_1;
	}



	public TextArea getTfObservacaoOS() {
		return tfObservacaoOS;
	}



	public void setTfObservacaoOS(TextArea tfObservacaoOS) {
		this.tfObservacaoOS = tfObservacaoOS;
	}



	public TextArea getTfObservacaoLocal() {
		return tfObservacaoLocal;
	}



	public void setTfObservacaoLocal(TextArea tfObservacaoLocal) {
		this.tfObservacaoLocal = tfObservacaoLocal;
	}

}