package dc.visao.ponto;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import org.vaadin.addons.maskedtextfield.MaskedTextField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.VerticalLayout;

import dc.entidade.geral.pessoal.ColaboradorEntity;
import dc.entidade.ponto.PontoHorarioAutorizado;
import dc.visao.framework.util.ComponentUtil;
import dc.visao.ponto.PontoHorarioFormView.TipoHorarioPonto;

public class PontoHorarioAutorizadoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private MaskedTextField txSaida04;
	@AutoGenerated
	private MaskedTextField txEntrada04;
	@AutoGenerated
	private MaskedTextField txSaida05;
	@AutoGenerated
	private MaskedTextField txEntrada05;
	@AutoGenerated
	private MaskedTextField txSaida03;
	@AutoGenerated
	private MaskedTextField txEntrada03;
	@AutoGenerated
	private MaskedTextField txSaida02;
	@AutoGenerated
	private MaskedTextField txEntrada02;
	@AutoGenerated
	private MaskedTextField txSaida01;
	@AutoGenerated
	private MaskedTextField txEntrada01;
	@AutoGenerated
	private MaskedTextField txHoraFechamentoDia;
	@AutoGenerated
	private MaskedTextField txCargaHoraria;
	@AutoGenerated
	private ComboBox cbmTipo;
	@AutoGenerated
	private MaskedTextField txDataHorario;
	@AutoGenerated
	private ComboBox cmbColaborador;

	private static final SimpleDateFormat dataHoraParser = new SimpleDateFormat(
			"MM/yyyy");

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PontoHorarioAutorizadoFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void preencheForm(PontoHorarioAutorizado currentBean) {
		txCargaHoraria.setValue(currentBean.getCargaHoraria());
		cmbColaborador.setValue(currentBean.getColaborador());

		txDataHorario.setValue(dataHoraParser.format(currentBean
				.getDataHorario()));

		txEntrada01.setValue(currentBean.getEntrada01());
		txEntrada02.setValue(currentBean.getEntrada02());
		txEntrada03.setValue(currentBean.getEntrada03());
		txEntrada04.setValue(currentBean.getEntrada04());
		txEntrada05.setValue(currentBean.getEntrada05());

		txSaida01.setValue(currentBean.getSaida01());
		txSaida02.setValue(currentBean.getSaida02());
		txSaida03.setValue(currentBean.getSaida03());
		txSaida04.setValue(currentBean.getSaida04());
		txSaida05.setValue(currentBean.getSaida05());

		txHoraFechamentoDia.setValue(currentBean.getHoraFechamentoDia());
		cbmTipo.setValue(TipoHorarioPonto.getTipo(currentBean.getTipo()));

	}

	public void preencheBean(PontoHorarioAutorizado currentBean) {
		currentBean.setCargaHoraria(txCargaHoraria.getValue());
		currentBean.setColaborador((ColaboradorEntity) cmbColaborador.getValue());

		try {
			currentBean.setDataHorario(dataHoraParser.parse(txDataHorario
					.getValue()));
		} catch (ParseException e) {
			e.printStackTrace();
		}
		currentBean.setEntrada01(txEntrada01.getValue());
		currentBean.setEntrada02(txEntrada02.getValue());
		currentBean.setEntrada03(txEntrada03.getValue());
		currentBean.setEntrada04(txEntrada04.getValue());
		currentBean.setEntrada05(txEntrada05.getValue());

		currentBean.setSaida01(txSaida01.getValue());
		currentBean.setSaida02(txSaida02.getValue());
		currentBean.setSaida03(txSaida03.getValue());
		currentBean.setSaida04(txSaida04.getValue());
		currentBean.setSaida05(txSaida05.getValue());

		currentBean.setHoraFechamentoDia(txHoraFechamentoDia.getValue());
		currentBean.setTipo(((TipoHorarioPonto) cbmTipo.getValue()).getCodigo());

	}

	public void carregarColaboradores(List<ColaboradorEntity> colaboradores) {
		this.cmbColaborador.removeAllItems();
		for (ColaboradorEntity colaborador : colaboradores) {
			this.cmbColaborador.addItem(colaborador);
		}
	}

	public void carregarTipo() {
		this.cbmTipo.removeAllItems();
		for (PontoHorarioFormView.TipoHorarioPonto tipo : PontoHorarioFormView.TipoHorarioPonto.values()) {
			this.cbmTipo.addItem(tipo);
		}

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);

		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setWidth("100%");
		gridLayout_1.setColumns(4);
		gridLayout_1.setRows(7);

		// cmbColaborador
		cmbColaborador = ComponentUtil.buildComboBox("Colaborador");
		gridLayout_1.addComponent(cmbColaborador, 0, 0);

		// txDataHorario
		txDataHorario = ComponentUtil.buildMaskedTextField("Data Horário",
				"##/####");

		gridLayout_1.addComponent(txDataHorario, 0, 1);

		// cbmTipo
		cbmTipo = ComponentUtil.buildComboBox("Tipo");
		gridLayout_1.addComponent(cbmTipo, 1, 1);

		// txCargaHoraria
		txCargaHoraria = ComponentUtil.buildMaskedTextField("Carga Horária",
				"##:##:##");
		gridLayout_1.addComponent(txCargaHoraria, 2, 1);

		// txHoraFechamentoDia
		txHoraFechamentoDia = ComponentUtil.buildMaskedTextField(
				"Hora Fechamento Dia", "##:##:##");
		gridLayout_1.addComponent(txHoraFechamentoDia, 3, 1);

		// txEntrada01
		txEntrada01 = ComponentUtil.buildMaskedTextField("Entrada01",
				"##:##:##");
		gridLayout_1.addComponent(txEntrada01, 0, 2);

		// txSaida01
		txSaida01 = ComponentUtil.buildMaskedTextField("Saida01", "##:##:##");
		gridLayout_1.addComponent(txSaida01, 1, 2);

		// txEntrada02
		txEntrada02 = ComponentUtil.buildMaskedTextField("Entrada02",
				"##:##:##");
		gridLayout_1.addComponent(txEntrada02, 0, 3);

		// txSaida02
		txSaida02 = ComponentUtil.buildMaskedTextField("Saída02", "##:##:##");
		gridLayout_1.addComponent(txSaida02, 1, 3);

		// txEntrada03
		txEntrada03 = ComponentUtil.buildMaskedTextField("Entrada03",
				"##:##:##");
		gridLayout_1.addComponent(txEntrada03, 0, 4);

		// txSaida03
		txSaida03 = ComponentUtil.buildMaskedTextField("Saída03", "##:##:##");
		gridLayout_1.addComponent(txSaida03, 1, 4);

		// txEntrada04
		txEntrada04 = ComponentUtil.buildMaskedTextField("Entrada04",
				"##:##:##");
		gridLayout_1.addComponent(txEntrada04, 0, 5);

		// txSaida04
		txSaida04 = ComponentUtil.buildMaskedTextField("Saída04", "##:##:##");
		gridLayout_1.addComponent(txSaida04, 1, 5);

		// txEntrada05
		txEntrada05 = ComponentUtil.buildMaskedTextField("Entrada05",
				"##:##:##");
		gridLayout_1.addComponent(txEntrada05, 0, 6);

		// txSaida05
		txSaida05 = ComponentUtil.buildMaskedTextField("Saída05", "##:##:##");
		gridLayout_1.addComponent(txSaida05, 1, 6);

		return gridLayout_1;
	}

	

	public MaskedTextField getTxSaida04() {
		return txSaida04;
	}

	public void setTxSaida04(MaskedTextField txSaida04) {
		this.txSaida04 = txSaida04;
	}

	public MaskedTextField getTxEntrada04() {
		return txEntrada04;
	}

	public void setTxEntrada04(MaskedTextField txEntrada04) {
		this.txEntrada04 = txEntrada04;
	}

	public MaskedTextField getTxSaida05() {
		return txSaida05;
	}

	public void setTxSaida05(MaskedTextField txSaida05) {
		this.txSaida05 = txSaida05;
	}

	public MaskedTextField getTxEntrada05() {
		return txEntrada05;
	}

	public void setTxEntrada05(MaskedTextField txEntrada05) {
		this.txEntrada05 = txEntrada05;
	}

	public MaskedTextField getTxSaida03() {
		return txSaida03;
	}

	public void setTxSaida03(MaskedTextField txSaida03) {
		this.txSaida03 = txSaida03;
	}

	public MaskedTextField getTxEntrada03() {
		return txEntrada03;
	}

	public void setTxEntrada03(MaskedTextField txEntrada03) {
		this.txEntrada03 = txEntrada03;
	}

	public MaskedTextField getTxSaida02() {
		return txSaida02;
	}

	public void setTxSaida02(MaskedTextField txSaida02) {
		this.txSaida02 = txSaida02;
	}

	public MaskedTextField getTxEntrada02() {
		return txEntrada02;
	}

	public void setTxEntrada02(MaskedTextField txEntrada02) {
		this.txEntrada02 = txEntrada02;
	}

	public MaskedTextField getTxSaida01() {
		return txSaida01;
	}

	public void setTxSaida01(MaskedTextField txSaida01) {
		this.txSaida01 = txSaida01;
	}

	public MaskedTextField getTxEntrada01() {
		return txEntrada01;
	}

	public void setTxEntrada01(MaskedTextField txEntrada01) {
		this.txEntrada01 = txEntrada01;
	}

	public MaskedTextField getTxHoraFechamentoDia() {
		return txHoraFechamentoDia;
	}

	public void setTxHoraFechamentoDia(MaskedTextField txHoraFechamentoDia) {
		this.txHoraFechamentoDia = txHoraFechamentoDia;
	}

	public MaskedTextField getTxCargaHoraria() {
		return txCargaHoraria;
	}

	public void setTxCargaHoraria(MaskedTextField txCargaHoraria) {
		this.txCargaHoraria = txCargaHoraria;
	}

	public ComboBox getCbmTipo() {
		return cbmTipo;
	}

	public void setCbmTipo(ComboBox cbmTipo) {
		this.cbmTipo = cbmTipo;
	}

	public MaskedTextField getTxDataHorario() {
		return txDataHorario;
	}

	public void setTxDataHorario(MaskedTextField txDataHorario) {
		this.txDataHorario = txDataHorario;
	}

	public ComboBox getCmbColaborador() {
		return cmbColaborador;
	}

	public void setCmbColaborador(ComboBox cmbColaborador) {
		this.cmbColaborador = cmbColaborador;
	}

	public static SimpleDateFormat getDatahoraparser() {
		return dataHoraParser;
	}
}