package dc.visao.geral.tabela;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.visao.framework.util.ComponentUtil;

public class CodigoGpsFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	
	@AutoGenerated
	private GridLayout fields;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextField txtCodigo;
	@AutoGenerated
	private TextArea txtDescricao;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CodigoGpsFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);
	
		return mainLayout;
	}

	
	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(4);
		fields.setColumns(4);
		
		txtCodigo = ComponentUtil.buildTextField("Código");
		txtCodigo.setImmediate(false);
		fields.addComponent(txtCodigo, 0, 0, 1,0);
		
		// txtDescricao
		txtDescricao = ComponentUtil.buildTextArea("Descrição");
		txtDescricao.setImmediate(false);
		fields.addComponent(txtDescricao, 0, 1, 1,1);
		
		return fields;

	}

	public GridLayout getMainLayout() {
		return fields;
	}

	public void setMainLayout(GridLayout fields) {
		this.fields = fields;
	}
	
	public TextField getTxtCodigo() {
		return txtCodigo;
	}

	public void setTxtCodigo(TextField txtCodigo) {
		this.txtCodigo = txtCodigo;
	}

	public VerticalLayout getVerticalLayout_1() {
		return mainLayout;
	}

	public void setVerticalLayout_1(VerticalLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public TextArea getTxtDescricao() {
		return txtDescricao;
	}

	public void setTxtDescricao(TextArea txtDescricao) {
		this.txtDescricao = txtDescricao;
	}
	
	

}
