package dc.visao.nfe;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.nfe.NotaFormController;

/**
 * 
 * 
 */

public class NotaFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private Panel panel_3;

	@AutoGenerated
	private VerticalLayout verticalLayout_4;

	@AutoGenerated
	private TabSheet tabSheet_1;

	@AutoGenerated
	private GridLayout gridLayout_3;

	@AutoGenerated
	private TextField textField_13;

	@AutoGenerated
	private GridLayout gridLayout_2;

	@AutoGenerated
	private TextField textField_12;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private TextField textField_11;

	@AutoGenerated
	private GridLayout gridLayout_21;

	@AutoGenerated
	private TextField textField_10;

	@AutoGenerated
	private GridLayout gridLayout_19;

	@AutoGenerated
	private TextField textField_8;

	@AutoGenerated
	private GridLayout gridLayout_20;

	@AutoGenerated
	private TextField textField_9;

	@AutoGenerated
	private GridLayout gridLayout_18;

	@AutoGenerated
	private TextField textField_7;

	@AutoGenerated
	private GridLayout gridLayout_17;

	@AutoGenerated
	private TextField textField_6;

	@AutoGenerated
	private GridLayout gridLayout_16;

	@AutoGenerated
	private TextField textField_5;

	@AutoGenerated
	private GridLayout gridLayout_15;

	@AutoGenerated
	private TextField textField_4;

	@AutoGenerated
	private GridLayout gridLayout_14;

	@AutoGenerated
	private TextField textField_1;

	@AutoGenerated
	private Panel panel_2;

	@AutoGenerated
	private VerticalLayout verticalLayout_3;

	@AutoGenerated
	private TabSheet tabSheet_2;

	@AutoGenerated
	private VerticalLayout verticalLayout_5;

	@AutoGenerated
	private Panel panel_5;

	@AutoGenerated
	private VerticalLayout verticalLayout_7;

	@AutoGenerated
	private GridLayout gridLayout_5;

	@AutoGenerated
	private TextField tfTcl;

	@AutoGenerated
	private Panel panel_4;

	@AutoGenerated
	private VerticalLayout verticalLayout_6;

	@AutoGenerated
	private GridLayout gridLayout_4;

	@AutoGenerated
	private TextField tfFormaPagamento;

	@AutoGenerated
	private TextField tfFormatoImpressaoDanfe;

	@AutoGenerated
	private TextField tfFinalidadeEmissao;

	@AutoGenerated
	private TextField tfTipoEmissao;

	@AutoGenerated
	private TextField tfTipoOperacao;

	@AutoGenerated
	private TextField tfHoraEntradaSaida;

	@AutoGenerated
	private TextField tfDataEntradaSaida;

	@AutoGenerated
	private TextField tfDataEmissao;

	@AutoGenerated
	private TextField tfNumero;

	@AutoGenerated
	private TextField tfSerie;

	@AutoGenerated
	private TextField tfCodigoNumerico;

	@AutoGenerated
	private TextField tfDigitoChaveAcesso;

	@AutoGenerated
	private TextField tfChaveAcesso;

	@AutoGenerated
	private TextField tfNaturezaOperacao;

	@AutoGenerated
	private TextField tfModeloNotaFiscal;

	@AutoGenerated
	private TextField tfVenda;

	@AutoGenerated
	private TextField tfOperacaoFiscal;

	@AutoGenerated
	private TextField tfOperacaoFiscalId;

	@AutoGenerated
	private TextField tfCpfVCnpj;

	@AutoGenerated
	private TextField tfRazaoSocialNome;

	@AutoGenerated
	private TextField tfCep;

	@AutoGenerated
	private TextField tfLogradouro;

	@AutoGenerated
	private TextField tfNumeroDestinatario;

	@AutoGenerated
	private TextField tfComplemento;

	@AutoGenerated
	private TextField tfBairro;

	@AutoGenerated
	private TextField tfCodigoIbge;

	@AutoGenerated
	private TextField tfCidade;

	@AutoGenerated
	private TextField tfUf;

	@AutoGenerated
	private TextField tfInscricaoEstadual;

	@AutoGenerated
	private TextField tfTelefone;

	@AutoGenerated
	private TextField tfSuframa;

	@AutoGenerated
	private TextField tfEmail;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private NotaFormController controller;

	public NotaFormView(NotaFormController controller) {
		this.controller = controller;

		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}

	public TextField getTfTcl() {
		return tfTcl;
	}

	public void setTfTcl(TextField tfTcl) {
		this.tfTcl = tfTcl;
	}

	public TextField getTfOperacaoFiscalId() {
		return tfOperacaoFiscalId;
	}

	public void setTfOperacaoFiscalId(TextField tfOperacaoFiscalId) {
		this.tfOperacaoFiscalId = tfOperacaoFiscalId;
	}

	public TextField getTfOperacaoFiscal() {
		return tfOperacaoFiscal;
	}

	public void setTfOperacaoFiscal(TextField tfOperacaoFiscal) {
		this.tfOperacaoFiscal = tfOperacaoFiscal;
	}

	public TextField getTfVenda() {
		return tfVenda;
	}

	public void setTfVenda(TextField tfVenda) {
		this.tfVenda = tfVenda;
	}

	public TextField getTfModeloNotaFiscal() {
		return tfModeloNotaFiscal;
	}

	public void setTfModeloNotaFiscal(TextField tfModeloNotaFiscal) {
		this.tfModeloNotaFiscal = tfModeloNotaFiscal;
	}

	public TextField getTfNaturezaOperacao() {
		return tfNaturezaOperacao;
	}

	public void setTfNaturezaOperacao(TextField tfNaturezaOperacao) {
		this.tfNaturezaOperacao = tfNaturezaOperacao;
	}

	public TextField getTfChaveAcesso() {
		return tfChaveAcesso;
	}

	public void setTfChaveAcesso(TextField tfChaveAcesso) {
		this.tfChaveAcesso = tfChaveAcesso;
	}

	public TextField getTfDigitoChaveAcesso() {
		return tfDigitoChaveAcesso;
	}

	public void setTfDigitoChaveAcesso(TextField tfDigitoChaveAcesso) {
		this.tfDigitoChaveAcesso = tfDigitoChaveAcesso;
	}

	public TextField getTfCodigoNumerico() {
		return tfCodigoNumerico;
	}

	public void setTfCodigoNumerico(TextField tfCodigoNumerico) {
		this.tfCodigoNumerico = tfCodigoNumerico;
	}

	public TextField getTfSerie() {
		return tfSerie;
	}

	public void setTfSerie(TextField tfSerie) {
		this.tfSerie = tfSerie;
	}

	public TextField getTfNumero() {
		return tfNumero;
	}

	public void setTfNumero(TextField tfNumero) {
		this.tfNumero = tfNumero;
	}

	public TextField getTfDataEmissao() {
		return tfDataEmissao;
	}

	public void setTfDataEmissao(TextField tfDataEmissao) {
		this.tfDataEmissao = tfDataEmissao;
	}

	public TextField getTfDataEntradaSaida() {
		return tfDataEntradaSaida;
	}

	public void setTfDataEntradaSaida(TextField tfDataEntradaSaida) {
		this.tfDataEntradaSaida = tfDataEntradaSaida;
	}

	public TextField getTfHoraEntradaSaida() {
		return tfHoraEntradaSaida;
	}

	public void setTfHoraEntradaSaida(TextField tfHoraEntradaSaida) {
		this.tfHoraEntradaSaida = tfHoraEntradaSaida;
	}

	public TextField getTfTipoOperacao() {
		return tfTipoOperacao;
	}

	public void setTfTipoOperacao(TextField tfTipoOperacao) {
		this.tfTipoOperacao = tfTipoOperacao;
	}

	public TextField getTfTipoEmissao() {
		return tfTipoEmissao;
	}

	public void setTfTipoEmissao(TextField tfTipoEmissao) {
		this.tfTipoEmissao = tfTipoEmissao;
	}

	public TextField getTfFinalidadeEmissao() {
		return tfFinalidadeEmissao;
	}

	public void setTfFinalidadeEmissao(TextField tfFinalidadeEmissao) {
		this.tfFinalidadeEmissao = tfFinalidadeEmissao;
	}

	public TextField getTfFormatoImpressaoDanfe() {
		return tfFormatoImpressaoDanfe;
	}

	public void setTfFormatoImpressaoDanfe(TextField tfFormatoImpressaoDanfe) {
		this.tfFormatoImpressaoDanfe = tfFormatoImpressaoDanfe;
	}

	public TextField getTfFormaPagamento() {
		return tfFormaPagamento;
	}

	public void setTfFormaPagamento(TextField tfFormaPagamento) {
		this.tfFormaPagamento = tfFormaPagamento;
	}

	public TextField getTfCpfVCnpj() {
		return tfCpfVCnpj;
	}

	public void setTfCpfVCnpj(TextField tfCpfVCnpj) {
		this.tfCpfVCnpj = tfCpfVCnpj;
	}

	public TextField getTfRazaoSocialNome() {
		return tfRazaoSocialNome;
	}

	public void setTfRazaoSocialNome(TextField tfRazaoSocialNome) {
		this.tfRazaoSocialNome = tfRazaoSocialNome;
	}

	public TextField getTfCep() {
		return tfCep;
	}

	public void setTfCep(TextField tfCep) {
		this.tfCep = tfCep;
	}

	public TextField getTfLogradouro() {
		return tfLogradouro;
	}

	public void setTfLogradouro(TextField tfLogradouro) {
		this.tfLogradouro = tfLogradouro;
	}

	public TextField getTfNumeroDestinatario() {
		return tfNumeroDestinatario;
	}

	public void setTfNumeroDestinatario(TextField tfNumeroDestinatario) {
		this.tfNumeroDestinatario = tfNumeroDestinatario;
	}

	public TextField getTfComplemento() {
		return tfComplemento;
	}

	public void setTfComplemento(TextField tfComplemento) {
		this.tfComplemento = tfComplemento;
	}

	public TextField getTfBairro() {
		return tfBairro;
	}

	public void setTfBairro(TextField tfBairro) {
		this.tfBairro = tfBairro;
	}

	public TextField getTfCodigoIbge() {
		return tfCodigoIbge;
	}

	public void setTfCodigoIbge(TextField tfCodigoIbge) {
		this.tfCodigoIbge = tfCodigoIbge;
	}

	public TextField getTfCidade() {
		return tfCidade;
	}

	public void setTfCidade(TextField tfCidade) {
		this.tfCidade = tfCidade;
	}

	public TextField getTfUf() {
		return tfUf;
	}

	public void setTfUf(TextField tfUf) {
		this.tfUf = tfUf;
	}

	public TextField getTfInscricaoEstadual() {
		return tfInscricaoEstadual;
	}

	public void setTfInscricaoEstadual(TextField tfInscricaoEstadual) {
		this.tfInscricaoEstadual = tfInscricaoEstadual;
	}

	public TextField getTfTelefone() {
		return tfTelefone;
	}

	public void setTfTelefone(TextField tfTelefone) {
		this.tfTelefone = tfTelefone;
	}

	public TextField getTfSuframa() {
		return tfSuframa;
	}

	public void setTfSuframa(TextField tfSuframa) {
		this.tfSuframa = tfSuframa;
	}

	public TextField getTfEmail() {
		return tfEmail;
	}

	public void setTfEmail(TextField tfEmail) {
		this.tfEmail = tfEmail;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// panel_2
		panel_2 = buildPanel_2();
		verticalLayout_2.addComponent(panel_2);

		// panel_3
		panel_3 = buildPanel_3();
		verticalLayout_2.addComponent(panel_3);

		return verticalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("100.0%");
		panel_2.setHeight("100.0%");

		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_2.setContent(verticalLayout_3);

		return panel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);

		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
		verticalLayout_3.addComponent(tabSheet_2);

		return verticalLayout_3;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(true);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("100.0%");

		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		tabSheet_2.addTab(verticalLayout_5, "Dados NF-e", null);

		return tabSheet_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(false);

		// panel_4
		panel_4 = buildPanel_4();
		verticalLayout_5.addComponent(panel_4);

		// panel_5
		panel_5 = buildPanel_5();
		verticalLayout_5.addComponent(panel_5);

		return verticalLayout_5;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setImmediate(false);
		panel_4.setWidth("100.0%");
		panel_4.setHeight("100.0%");

		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		panel_4.setContent(verticalLayout_6);

		return panel_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("100.0%");
		verticalLayout_6.setHeight("100.0%");
		verticalLayout_6.setMargin(false);

		// gridLayout_4
		gridLayout_4 = buildGridLayout_4();
		verticalLayout_6.addComponent(gridLayout_4);

		return verticalLayout_6;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_4() {
		// common part: create layout
		gridLayout_4 = new GridLayout();
		gridLayout_4.setImmediate(false);
		gridLayout_4.setWidth("100.0%");
		gridLayout_4.setHeight("100.0%");
		gridLayout_4.setMargin(false);
		gridLayout_4.setColumns(5);
		gridLayout_4.setRows(5);

		// tfOperacaoFiscalId
		tfOperacaoFiscalId = new TextField();
		tfOperacaoFiscalId.setCaption("Operação fiscal (ID):");
		tfOperacaoFiscalId.setImmediate(false);
		tfOperacaoFiscalId.setWidth("-1px");
		tfOperacaoFiscalId.setHeight("-1px");
		gridLayout_4.addComponent(tfOperacaoFiscalId, 0, 0);

		// tfOperacaoFiscal
		tfOperacaoFiscal = new TextField();
		tfOperacaoFiscal.setCaption("Operação fiscal:");
		tfOperacaoFiscal.setImmediate(false);
		tfOperacaoFiscal.setWidth("-1px");
		tfOperacaoFiscal.setHeight("-1px");
		gridLayout_4.addComponent(tfOperacaoFiscal, 1, 0);

		// tfVenda
		tfVenda = new TextField();
		tfVenda.setCaption("Venda:");
		tfVenda.setImmediate(false);
		tfVenda.setWidth("-1px");
		tfVenda.setHeight("-1px");
		gridLayout_4.addComponent(tfVenda, 2, 0);

		// tfModeloNotaFiscal
		tfModeloNotaFiscal = new TextField();
		tfModeloNotaFiscal.setCaption("Modelo de nota fiscal:");
		tfModeloNotaFiscal.setImmediate(false);
		tfModeloNotaFiscal.setWidth("-1px");
		tfModeloNotaFiscal.setHeight("-1px");
		gridLayout_4.addComponent(tfModeloNotaFiscal, 3, 0);

		// tfNaturezaOperacao
		tfNaturezaOperacao = new TextField();
		tfNaturezaOperacao.setCaption("Natureza da operação:");
		tfNaturezaOperacao.setImmediate(false);
		tfNaturezaOperacao.setWidth("-1px");
		tfNaturezaOperacao.setHeight("-1px");
		gridLayout_4.addComponent(tfNaturezaOperacao, 4, 0);

		// tfChaveAcesso
		tfChaveAcesso = new TextField();
		tfChaveAcesso.setCaption("Chave de acesso:");
		tfChaveAcesso.setImmediate(false);
		tfChaveAcesso.setWidth("-1px");
		tfChaveAcesso.setHeight("-1px");
		gridLayout_4.addComponent(tfChaveAcesso, 0, 1);

		// tfDigitoChaveAcesso
		tfDigitoChaveAcesso = new TextField();
		tfDigitoChaveAcesso.setCaption("DV:");
		tfDigitoChaveAcesso.setImmediate(false);
		tfDigitoChaveAcesso.setWidth("-1px");
		tfDigitoChaveAcesso.setHeight("-1px");
		gridLayout_4.addComponent(tfDigitoChaveAcesso, 1, 1);

		// tfCodigoNumerico
		tfCodigoNumerico = new TextField();
		tfCodigoNumerico.setCaption("Código numérico:");
		tfCodigoNumerico.setImmediate(false);
		tfCodigoNumerico.setWidth("-1px");
		tfCodigoNumerico.setHeight("-1px");
		gridLayout_4.addComponent(tfCodigoNumerico, 2, 1);

		// tfSerie
		tfSerie = new TextField();
		tfSerie.setCaption("Série:");
		tfSerie.setImmediate(false);
		tfSerie.setWidth("-1px");
		tfSerie.setHeight("-1px");
		gridLayout_4.addComponent(tfSerie, 3, 1);

		// tfNumero
		tfNumero = new TextField();
		tfNumero.setCaption("Número:");
		tfNumero.setImmediate(false);
		tfNumero.setWidth("-1px");
		tfNumero.setHeight("-1px");
		gridLayout_4.addComponent(tfNumero, 4, 1);

		// tfDataEmissao
		tfDataEmissao = new TextField();
		tfDataEmissao.setCaption("Data da emissão:");
		tfDataEmissao.setImmediate(false);
		tfDataEmissao.setWidth("-1px");
		tfDataEmissao.setHeight("-1px");
		gridLayout_4.addComponent(tfDataEmissao, 0, 2);

		// tfDataEntradaSaida
		tfDataEntradaSaida = new TextField();
		tfDataEntradaSaida.setCaption("Data (Entrada / saída):");
		tfDataEntradaSaida.setImmediate(false);
		tfDataEntradaSaida.setWidth("-1px");
		tfDataEntradaSaida.setHeight("-1px");
		gridLayout_4.addComponent(tfDataEntradaSaida, 1, 2);

		// tfHoraEntradaSaida
		tfHoraEntradaSaida = new TextField();
		tfHoraEntradaSaida.setCaption("Hora (Entrada / saída):");
		tfHoraEntradaSaida.setImmediate(false);
		tfHoraEntradaSaida.setWidth("-1px");
		tfHoraEntradaSaida.setHeight("-1px");
		gridLayout_4.addComponent(tfHoraEntradaSaida, 2, 2);

		// tfTipoOperacao
		tfTipoOperacao = new TextField();
		tfTipoOperacao.setCaption("Tipo de operação:");
		tfTipoOperacao.setImmediate(false);
		tfTipoOperacao.setWidth("-1px");
		tfTipoOperacao.setHeight("-1px");
		gridLayout_4.addComponent(tfTipoOperacao, 3, 2);

		// tfTipoEmissao
		tfTipoEmissao = new TextField();
		tfTipoEmissao.setCaption("Tipo de emissão:");
		tfTipoEmissao.setImmediate(false);
		tfTipoEmissao.setWidth("-1px");
		tfTipoEmissao.setHeight("-1px");
		gridLayout_4.addComponent(tfTipoEmissao, 4, 2);

		// tfFinalidadeEmissao
		tfFinalidadeEmissao = new TextField();
		tfFinalidadeEmissao.setCaption("Finalidade de emissão:");
		tfFinalidadeEmissao.setImmediate(false);
		tfFinalidadeEmissao.setWidth("-1px");
		tfFinalidadeEmissao.setHeight("-1px");
		gridLayout_4.addComponent(tfFinalidadeEmissao, 0, 3);

		// tfFormatoImpressaoDanfe
		tfFormatoImpressaoDanfe = new TextField();
		tfFormatoImpressaoDanfe.setCaption("Formato da impressão DANFE:");
		tfFormatoImpressaoDanfe.setImmediate(false);
		tfFormatoImpressaoDanfe.setWidth("-1px");
		tfFormatoImpressaoDanfe.setHeight("-1px");
		gridLayout_4.addComponent(tfFormatoImpressaoDanfe, 1, 3);

		// tfFormaPagamento
		tfFormaPagamento = new TextField();
		tfFormaPagamento.setCaption("Forma de pagamento:");
		tfFormaPagamento.setImmediate(false);
		tfFormaPagamento.setWidth("-1px");
		tfFormaPagamento.setHeight("-1px");
		gridLayout_4.addComponent(tfFormaPagamento, 2, 3);

		return gridLayout_4;
	}

	@AutoGenerated
	private Panel buildPanel_5() {
		// common part: create layout
		panel_5 = new Panel();
		panel_5.setImmediate(false);
		panel_5.setWidth("100.0%");
		panel_5.setHeight("100.0%");

		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		panel_5.setContent(verticalLayout_7);

		return panel_5;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("100.0%");
		verticalLayout_7.setHeight("100.0%");
		verticalLayout_7.setMargin(false);

		// gridLayout_5
		gridLayout_5 = buildGridLayout_5();
		verticalLayout_7.addComponent(gridLayout_5);

		return verticalLayout_7;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_5() {
		// common part: create layout
		gridLayout_5 = new GridLayout();
		gridLayout_5.setImmediate(false);
		gridLayout_5.setWidth("100.0%");
		gridLayout_5.setHeight("100.0%");
		gridLayout_5.setMargin(false);
		gridLayout_5.setColumns(5);
		gridLayout_5.setRows(5);

		// tfTcl
		tfTcl = new TextField();
		tfTcl.setCaption("Tcl");
		tfTcl.setImmediate(false);
		tfTcl.setWidth("-1px");
		tfTcl.setHeight("-1px");
		gridLayout_5.addComponent(tfTcl, 0, 0);

		// tfCpfVCnpj
		tfCpfVCnpj = new TextField();
		tfCpfVCnpj.setCaption("CPF / CNPJ:");
		tfCpfVCnpj.setImmediate(false);
		tfCpfVCnpj.setWidth("-1px");
		tfCpfVCnpj.setHeight("-1px");
		gridLayout_5.addComponent(tfCpfVCnpj, 1, 0);

		// tfRazaoSocialNome
		tfRazaoSocialNome = new TextField();
		tfRazaoSocialNome.setCaption("Razão social / nome:");
		tfRazaoSocialNome.setImmediate(false);
		tfRazaoSocialNome.setWidth("-1px");
		tfRazaoSocialNome.setHeight("-1px");
		gridLayout_5.addComponent(tfRazaoSocialNome, 2, 0);

		// tfCep
		tfCep = new TextField();
		tfCep.setCaption("CEP:");
		tfCep.setImmediate(false);
		tfCep.setWidth("-1px");
		tfCep.setHeight("-1px");
		gridLayout_5.addComponent(tfCep, 0, 1);

		// tfLogradouro
		tfLogradouro = new TextField();
		tfLogradouro.setCaption("Logradouro:");
		tfLogradouro.setImmediate(false);
		tfLogradouro.setWidth("-1px");
		tfLogradouro.setHeight("-1px");
		gridLayout_5.addComponent(tfLogradouro, 1, 1);

		// tfNumeroDestinatario
		tfNumeroDestinatario = new TextField();
		tfNumeroDestinatario.setCaption("Número:");
		tfNumeroDestinatario.setImmediate(false);
		tfNumeroDestinatario.setWidth("-1px");
		tfNumeroDestinatario.setHeight("-1px");
		gridLayout_5.addComponent(tfNumeroDestinatario, 2, 1);

		// tfComplemento
		tfComplemento = new TextField();
		tfComplemento.setCaption("Complemento:");
		tfComplemento.setImmediate(false);
		tfComplemento.setWidth("-1px");
		tfComplemento.setHeight("-1px");
		gridLayout_5.addComponent(tfComplemento, 3, 1);

		// tfBairro
		tfBairro = new TextField();
		tfBairro.setCaption("Bairro:");
		tfBairro.setImmediate(false);
		tfBairro.setWidth("-1px");
		tfBairro.setHeight("-1px");
		gridLayout_5.addComponent(tfBairro, 0, 2);

		// tfCodigoIbge
		tfCodigoIbge = new TextField();
		tfCodigoIbge.setCaption("Código do IBGE:");
		tfCodigoIbge.setImmediate(false);
		tfCodigoIbge.setWidth("-1px");
		tfCodigoIbge.setHeight("-1px");
		gridLayout_5.addComponent(tfCodigoIbge, 1, 2);

		// tfCidade
		tfCidade = new TextField();
		tfCidade.setCaption("Cidade:");
		tfCidade.setImmediate(false);
		tfCidade.setWidth("-1px");
		tfCidade.setHeight("-1px");
		gridLayout_5.addComponent(tfCidade, 2, 2);

		// tfUf
		tfUf = new TextField();
		tfUf.setCaption("UF:");
		tfUf.setImmediate(false);
		tfUf.setWidth("-1px");
		tfUf.setHeight("-1px");
		gridLayout_5.addComponent(tfUf, 3, 2);

		// tfInscricaoEstadual
		tfInscricaoEstadual = new TextField();
		tfInscricaoEstadual.setCaption("Inscrição estadual:");
		tfInscricaoEstadual.setImmediate(false);
		tfInscricaoEstadual.setWidth("-1px");
		tfInscricaoEstadual.setHeight("-1px");
		gridLayout_5.addComponent(tfInscricaoEstadual, 4, 2);

		// tfTelefone
		tfTelefone = new TextField();
		tfTelefone.setCaption("Telefone:");
		tfTelefone.setImmediate(false);
		tfTelefone.setWidth("-1px");
		tfTelefone.setHeight("-1px");
		gridLayout_5.addComponent(tfTelefone, 0, 3);

		// tfSuframa
		tfSuframa = new TextField();
		tfSuframa.setCaption("Suframa:");
		tfSuframa.setImmediate(false);
		tfSuframa.setWidth("-1px");
		tfSuframa.setHeight("-1px");
		gridLayout_5.addComponent(tfSuframa, 1, 3);

		// tfEmail
		tfEmail = new TextField();
		tfEmail.setCaption("E-mail:");
		tfEmail.setImmediate(false);
		tfEmail.setWidth("-1px");
		tfEmail.setHeight("-1px");
		gridLayout_5.addComponent(tfEmail, 2, 3);

		return gridLayout_5;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setImmediate(false);
		panel_3.setWidth("100.0%");
		panel_3.setHeight("100.0%");

		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panel_3.setContent(verticalLayout_4);

		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(false);

		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		verticalLayout_4.addComponent(tabSheet_1);

		return verticalLayout_4;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");

		// gridLayout_14
		gridLayout_14 = buildGridLayout_14();
		tabSheet_1.addTab(gridLayout_14, "ICMS", null);

		// gridLayout_15
		gridLayout_15 = buildGridLayout_15();
		tabSheet_1.addTab(gridLayout_15, "PIS", null);

		// gridLayout_16
		gridLayout_16 = buildGridLayout_16();
		tabSheet_1.addTab(gridLayout_16, "COFINS", null);

		// gridLayout_17
		gridLayout_17 = buildGridLayout_17();
		tabSheet_1.addTab(gridLayout_17, "IPI", null);

		// gridLayout_18
		gridLayout_18 = buildGridLayout_18();
		tabSheet_1.addTab(gridLayout_18, "Imposto importação", null);

		// gridLayout_20
		gridLayout_20 = buildGridLayout_20();
		tabSheet_1.addTab(gridLayout_20, "Combustível", null);

		// gridLayout_19
		gridLayout_19 = buildGridLayout_19();
		tabSheet_1.addTab(gridLayout_19, "ISSQN", null);

		// gridLayout_21
		gridLayout_21 = buildGridLayout_21();
		tabSheet_1.addTab(gridLayout_21, "Veículo", null);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		tabSheet_1.addTab(gridLayout_1, "Medicamentos", null);

		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		tabSheet_1.addTab(gridLayout_2, "Armamento", null);

		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		tabSheet_1.addTab(gridLayout_3, "Declaração importação", null);

		return tabSheet_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_14() {
		// common part: create layout
		gridLayout_14 = new GridLayout();
		gridLayout_14.setImmediate(false);
		gridLayout_14.setWidth("100.0%");
		gridLayout_14.setHeight("100.0%");
		gridLayout_14.setMargin(false);

		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		gridLayout_14.addComponent(textField_1, 0, 0);

		return gridLayout_14;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_15() {
		// common part: create layout
		gridLayout_15 = new GridLayout();
		gridLayout_15.setImmediate(false);
		gridLayout_15.setWidth("100.0%");
		gridLayout_15.setHeight("100.0%");
		gridLayout_15.setMargin(false);

		// textField_4
		textField_4 = new TextField();
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		gridLayout_15.addComponent(textField_4, 0, 0);

		return gridLayout_15;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_16() {
		// common part: create layout
		gridLayout_16 = new GridLayout();
		gridLayout_16.setImmediate(false);
		gridLayout_16.setWidth("100.0%");
		gridLayout_16.setHeight("100.0%");
		gridLayout_16.setMargin(false);

		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("-1px");
		textField_5.setHeight("-1px");
		gridLayout_16.addComponent(textField_5, 0, 0);

		return gridLayout_16;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_17() {
		// common part: create layout
		gridLayout_17 = new GridLayout();
		gridLayout_17.setImmediate(false);
		gridLayout_17.setWidth("100.0%");
		gridLayout_17.setHeight("100.0%");
		gridLayout_17.setMargin(false);

		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("-1px");
		textField_6.setHeight("-1px");
		gridLayout_17.addComponent(textField_6, 0, 0);

		return gridLayout_17;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_18() {
		// common part: create layout
		gridLayout_18 = new GridLayout();
		gridLayout_18.setImmediate(false);
		gridLayout_18.setWidth("100.0%");
		gridLayout_18.setHeight("100.0%");
		gridLayout_18.setMargin(false);

		// textField_7
		textField_7 = new TextField();
		textField_7.setImmediate(false);
		textField_7.setWidth("-1px");
		textField_7.setHeight("-1px");
		gridLayout_18.addComponent(textField_7, 0, 0);

		return gridLayout_18;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_20() {
		// common part: create layout
		gridLayout_20 = new GridLayout();
		gridLayout_20.setImmediate(false);
		gridLayout_20.setWidth("100.0%");
		gridLayout_20.setHeight("100.0%");
		gridLayout_20.setMargin(false);

		// textField_9
		textField_9 = new TextField();
		textField_9.setImmediate(false);
		textField_9.setWidth("-1px");
		textField_9.setHeight("-1px");
		gridLayout_20.addComponent(textField_9, 0, 0);

		return gridLayout_20;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_19() {
		// common part: create layout
		gridLayout_19 = new GridLayout();
		gridLayout_19.setImmediate(false);
		gridLayout_19.setWidth("100.0%");
		gridLayout_19.setHeight("100.0%");
		gridLayout_19.setMargin(false);

		// textField_8
		textField_8 = new TextField();
		textField_8.setImmediate(false);
		textField_8.setWidth("-1px");
		textField_8.setHeight("-1px");
		gridLayout_19.addComponent(textField_8, 0, 0);

		return gridLayout_19;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_21() {
		// common part: create layout
		gridLayout_21 = new GridLayout();
		gridLayout_21.setImmediate(false);
		gridLayout_21.setWidth("100.0%");
		gridLayout_21.setHeight("100.0%");
		gridLayout_21.setMargin(false);

		// textField_10
		textField_10 = new TextField();
		textField_10.setImmediate(false);
		textField_10.setWidth("-1px");
		textField_10.setHeight("-1px");
		gridLayout_21.addComponent(textField_10, 0, 0);

		return gridLayout_21;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);

		// textField_11
		textField_11 = new TextField();
		textField_11.setImmediate(false);
		textField_11.setWidth("-1px");
		textField_11.setHeight("-1px");
		gridLayout_1.addComponent(textField_11, 0, 0);

		return gridLayout_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("100.0%");
		gridLayout_2.setHeight("100.0%");
		gridLayout_2.setMargin(false);

		// textField_12
		textField_12 = new TextField();
		textField_12.setImmediate(false);
		textField_12.setWidth("-1px");
		textField_12.setHeight("-1px");
		gridLayout_2.addComponent(textField_12, 0, 0);

		return gridLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("100.0%");
		gridLayout_3.setHeight("100.0%");
		gridLayout_3.setMargin(false);

		// textField_13
		textField_13 = new TextField();
		textField_13.setImmediate(false);
		textField_13.setWidth("-1px");
		textField_13.setHeight("-1px");
		gridLayout_3.addComponent(textField_13, 0, 0);

		return gridLayout_3;
	}

}