package dc.visao.geral.diverso;

import org.vaadin.addons.maskedtextfield.MaskedTextField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.geral.diverso.CepFormController;
import dc.entidade.geral.diverso.UfEntity;
import dc.visao.framework.component.manytoonecombo.ManyToOneComboField;
import dc.visao.framework.util.ComponentUtil;

public class CepFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField tfCodigoIbgeMunicipio;

	@AutoGenerated
	private TextField tfMunicipio;

	@AutoGenerated
	private TextField tfBairro;

	@AutoGenerated
	private TextField tfComplemento;

	@AutoGenerated
	private TextField tfLogradouro;

	@AutoGenerated
	private MaskedTextField tfCep;

	@AutoGenerated
	private ManyToOneComboField<UfEntity> mocUf;

	private CepFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public CepFormView(CepFormController controller) {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	public TextField getTfCodigoIbgeMunicipio() {
		return tfCodigoIbgeMunicipio;
	}

	public void setTfCodigoIbgeMunicipio(TextField tfCodigoIbgeMunicipio) {
		this.tfCodigoIbgeMunicipio = tfCodigoIbgeMunicipio;
	}

	public TextField getTfMunicipio() {
		return tfMunicipio;
	}

	public void setTfMunicipio(TextField tfMunicipio) {
		this.tfMunicipio = tfMunicipio;
	}

	public TextField getTfBairro() {
		return tfBairro;
	}

	public void setTfBairro(TextField tfBairro) {
		this.tfBairro = tfBairro;
	}

	public TextField getTfComplemento() {
		return tfComplemento;
	}

	public void setTfComplemento(TextField tfComplemento) {
		this.tfComplemento = tfComplemento;
	}

	public TextField getTfLogradouro() {
		return tfLogradouro;
	}

	public void setTfLogradouro(TextField tfLogradouro) {
		this.tfLogradouro = tfLogradouro;
	}

	public MaskedTextField getTfCep() {
		return tfCep;
	}

	public void setTfCep(MaskedTextField tfCep) {
		this.tfCep = tfCep;
	}

	public ManyToOneComboField<UfEntity> getMocUf() {
		return mocUf;
	}

	public void setMocUf(ManyToOneComboField<UfEntity> mocUf) {
		this.mocUf = mocUf;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);

		return mainLayout;
	}

	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(5);
		fields.setColumns(5);

		// tfCep
		tfCep = ComponentUtil.buildMaskedTextField("CEP", "#####-###");
		tfCep.setMaskClientOnly(true);
		tfCep.setImmediate(false);
		fields.addComponent(tfCep, 0, 0);

		// tfLogradouro
		tfLogradouro = ComponentUtil.buildTextField("Logradouro");
		fields.addComponent(tfLogradouro, 0, 1, 1,1);

		// tfComplemento
		tfComplemento = ComponentUtil.buildTextField("Complemento");
		tfComplemento.setImmediate(false);
		fields.addComponent(tfComplemento, 2, 1, 3,1);

		// tfBairro
		tfBairro = ComponentUtil.buildTextField("Bairro");
		tfBairro.setImmediate(false);
		fields.addComponent(tfBairro, 0, 2);

		// tfMunicipio
		tfMunicipio = ComponentUtil.buildTextField("Município");
		tfMunicipio.setImmediate(false);
		fields.addComponent(tfMunicipio, 1, 2);

		// mocUf
		mocUf = new ManyToOneComboField<>(UfEntity.class);
		mocUf.setCaption("UF");
		fields.addComponent(mocUf, 0, 3);

		// tfCodigoIbgeMunicipio
		tfCodigoIbgeMunicipio = ComponentUtil.buildTextField("IBGE Município");
		tfCodigoIbgeMunicipio.setImmediate(false);
		fields.addComponent(tfCodigoIbgeMunicipio, 1, 3);

		return fields;
	}

}