package dc.visao.geral.diverso;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class CidadeFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField tfCodigoIbge;

	@AutoGenerated
	private TextField tfNome;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public CidadeFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public TextField getTfCodigoIbge() {
		return tfCodigoIbge;
	}

	public void setTfCodigoIbge(TextField tfCodigoIbge) {
		this.tfCodigoIbge = tfCodigoIbge;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// txtNome
		tfNome = new TextField();
		tfNome.setCaption("Nome");
		tfNome.setImmediate(false);
		tfNome.setWidth("-1px");
		tfNome.setHeight("-1px");
		mainLayout.addComponent(tfNome);

		// txtCodigoIBGE
		tfCodigoIbge = new TextField();
		tfCodigoIbge.setCaption("Código IBGE");
		tfCodigoIbge.setImmediate(false);
		tfCodigoIbge.setWidth("-1px");
		tfCodigoIbge.setHeight("-1px");
		mainLayout.addComponent(tfCodigoIbge);

		return mainLayout;
	}

}