package dc.visao.folhapagamento.ausencia;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.folhapagamento.ausencia.FeriasPeriodoAquisitivoFormController;
import dc.entidade.geral.pessoal.ColaboradorEntity;

public class FeriasPeriodoAquisitivoFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private PopupDateField pdfDataInicio;

	@AutoGenerated
	private TextField tfSituacao;

	@AutoGenerated
	private PopupDateField pdfLimiteParaGozo;

	@AutoGenerated
	private TextField tfDescontarFaltas;

	@AutoGenerated
	private TextField tfDesconsiderarAfastamento;

	@AutoGenerated
	private TextField tfAfastamentoPrevidencia;

	@AutoGenerated
	private TextField tfAfastamentoSemRemun;

	@AutoGenerated
	private TextField tfAfastamentoComRemun;

	@AutoGenerated
	private TextField tfDiasDireito;

	@AutoGenerated
	private TextField tfDiasGozados;

	@AutoGenerated
	private TextField tfDiasFaltas;

	@AutoGenerated
	private TextField tfDiasRestantes;

	@AutoGenerated
	private PopupDateField pdfDataFim;

	@AutoGenerated
	private ComboBox cbColaborador;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private FeriasPeriodoAquisitivoFormController controller;

	public FeriasPeriodoAquisitivoFormView(
			final FeriasPeriodoAquisitivoFormController controller) {
		this.controller = controller;

		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}

	public PopupDateField getPdfDataInicio() {
		return pdfDataInicio;
	}

	public void setPdfDataInicio(PopupDateField pdfDataInicio) {
		this.pdfDataInicio = pdfDataInicio;
	}

	public TextField getTfSituacao() {
		return tfSituacao;
	}

	public void setTfSituacao(TextField tfSituacao) {
		this.tfSituacao = tfSituacao;
	}

	public PopupDateField getPdfLimiteParaGozo() {
		return pdfLimiteParaGozo;
	}

	public void setPdfLimiteParaGozo(PopupDateField pdfLimiteParaGozo) {
		this.pdfLimiteParaGozo = pdfLimiteParaGozo;
	}

	public TextField getTfDescontarFaltas() {
		return tfDescontarFaltas;
	}

	public void setTfDescontarFaltas(TextField tfDescontarFaltas) {
		this.tfDescontarFaltas = tfDescontarFaltas;
	}

	public TextField getTfDesconsiderarAfastamento() {
		return tfDesconsiderarAfastamento;
	}

	public void setTfDesconsiderarAfastamento(
			TextField tfDesconsiderarAfastamento) {
		this.tfDesconsiderarAfastamento = tfDesconsiderarAfastamento;
	}

	public TextField getTfAfastamentoPrevidencia() {
		return tfAfastamentoPrevidencia;
	}

	public void setTfAfastamentoPrevidencia(TextField tfAfastamentoPrevidencia) {
		this.tfAfastamentoPrevidencia = tfAfastamentoPrevidencia;
	}

	public TextField getTfAfastamentoSemRemun() {
		return tfAfastamentoSemRemun;
	}

	public void setTfAfastamentoSemRemun(TextField tfAfastamentoSemRemun) {
		this.tfAfastamentoSemRemun = tfAfastamentoSemRemun;
	}

	public TextField getTfAfastamentoComRemun() {
		return tfAfastamentoComRemun;
	}

	public void setTfAfastamentoComRemun(TextField tfAfastamentoComRemun) {
		this.tfAfastamentoComRemun = tfAfastamentoComRemun;
	}

	public TextField getTfDiasDireito() {
		return tfDiasDireito;
	}

	public void setTfDiasDireito(TextField tfDiasDireito) {
		this.tfDiasDireito = tfDiasDireito;
	}

	public TextField getTfDiasGozados() {
		return tfDiasGozados;
	}

	public void setTfDiasGozados(TextField tfDiasGozados) {
		this.tfDiasGozados = tfDiasGozados;
	}

	public TextField getTfDiasFaltas() {
		return tfDiasFaltas;
	}

	public void setTfDiasFaltas(TextField tfDiasFaltas) {
		this.tfDiasFaltas = tfDiasFaltas;
	}

	public TextField getTfDiasRestantes() {
		return tfDiasRestantes;
	}

	public void setTfDiasRestantes(TextField tfDiasRestantes) {
		this.tfDiasRestantes = tfDiasRestantes;
	}

	public PopupDateField getPdfDataFim() {
		return pdfDataFim;
	}

	public void setPdfDataFim(PopupDateField pdfDataFim) {
		this.pdfDataFim = pdfDataFim;
	}

	public ComboBox getCbColaborador() {
		return cbColaborador;
	}

	public void setCbColaborador(ComboBox cbColaborador) {
		this.cbColaborador = cbColaborador;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_2.addComponent(gridLayout_1);

		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		// gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setRows(20);
		gridLayout_1.setColumns(2);

		// pdfDataInicio
		pdfDataInicio = new PopupDateField();
		pdfDataInicio.setCaption("Data início:");
		pdfDataInicio.setImmediate(false);
		pdfDataInicio.setWidth("175px");
		pdfDataInicio.setHeight("-1px");
		gridLayout_1.addComponent(pdfDataInicio, 0, 1);

		// tfSituacao
		tfSituacao = new TextField();
		tfSituacao.setCaption("Situação:");
		tfSituacao.setImmediate(false);
		tfSituacao.setWidth("175px");
		tfSituacao.setHeight("-1px");
		tfSituacao.setSizeFull();
		tfSituacao.setNullRepresentation("");
		gridLayout_1.addComponent(tfSituacao, 1, 1);

		// pdfLimiteParaGozo
		pdfLimiteParaGozo = new PopupDateField();
		pdfLimiteParaGozo.setCaption("Limite para gozo:");
		pdfLimiteParaGozo.setImmediate(false);
		pdfLimiteParaGozo.setWidth("175px");
		pdfLimiteParaGozo.setHeight("-1px");
		gridLayout_1.addComponent(pdfLimiteParaGozo, 0, 2);

		// tfDescontarFaltas
		tfDescontarFaltas = new TextField();
		tfDescontarFaltas.setCaption("Desconsiderar faltas:");
		tfDescontarFaltas.setImmediate(false);
		tfDescontarFaltas.setWidth("175px");
		tfDescontarFaltas.setHeight("-1px");
		tfDescontarFaltas.setSizeFull();
		tfDescontarFaltas.setNullRepresentation("");
		gridLayout_1.addComponent(tfDescontarFaltas, 1, 2);

		// tfDesconsiderarAfastamento
		tfDesconsiderarAfastamento = new TextField();
		tfDesconsiderarAfastamento.setCaption("Desconsiderar afastamento:");
		tfDesconsiderarAfastamento.setImmediate(false);
		tfDesconsiderarAfastamento.setWidth("175px");
		tfDesconsiderarAfastamento.setHeight("-1px");
		tfDesconsiderarAfastamento.setSizeFull();
		tfDesconsiderarAfastamento.setNullRepresentation("");
		gridLayout_1.addComponent(tfDesconsiderarAfastamento, 0, 3);

		// tfAfastamentoPrevidencia
		tfAfastamentoPrevidencia = new TextField();
		tfAfastamentoPrevidencia.setCaption("Afastamento previdência:");
		tfAfastamentoPrevidencia.setImmediate(false);
		tfAfastamentoPrevidencia.setWidth("175px");
		tfAfastamentoPrevidencia.setHeight("-1px");
		tfAfastamentoPrevidencia.setSizeFull();
		tfAfastamentoPrevidencia.setNullRepresentation("");
		gridLayout_1.addComponent(tfAfastamentoPrevidencia, 1, 3);

		// tfAfastamentoSemRemun
		tfAfastamentoSemRemun = new TextField();
		tfAfastamentoSemRemun.setCaption("Afastamento sem remuneração:");
		tfAfastamentoSemRemun.setImmediate(false);
		tfAfastamentoSemRemun.setWidth("175px");
		tfAfastamentoSemRemun.setHeight("-1px");
		tfAfastamentoSemRemun.setSizeFull();
		tfAfastamentoSemRemun.setNullRepresentation("");
		gridLayout_1.addComponent(tfAfastamentoSemRemun, 0, 4);

		// tfAfastamentoComRemun
		tfAfastamentoComRemun = new TextField();
		tfAfastamentoComRemun.setCaption("Afastamento com remuneração:");
		tfAfastamentoComRemun.setImmediate(false);
		tfAfastamentoComRemun.setWidth("175px");
		tfAfastamentoComRemun.setHeight("-1px");
		tfAfastamentoComRemun.setSizeFull();
		tfAfastamentoComRemun.setNullRepresentation("");
		gridLayout_1.addComponent(tfAfastamentoComRemun, 1, 4);

		// tfDiasDireito
		tfDiasDireito = new TextField();
		tfDiasDireito.setCaption("Dias de direito:");
		tfDiasDireito.setImmediate(false);
		tfDiasDireito.setWidth("175px");
		tfDiasDireito.setHeight("-1px");
		tfDiasDireito.setSizeFull();
		tfDiasDireito.setNullRepresentation("");
		gridLayout_1.addComponent(tfDiasDireito, 0, 5);

		// tfDiasGozados
		tfDiasGozados = new TextField();
		tfDiasGozados.setCaption("Dias gozados:");
		tfDiasGozados.setImmediate(false);
		tfDiasGozados.setWidth("175px");
		tfDiasGozados.setHeight("-1px");
		tfDiasGozados.setSizeFull();
		tfDiasGozados.setNullRepresentation("");
		gridLayout_1.addComponent(tfDiasGozados, 1, 5);

		// tfDiasFaltas
		tfDiasFaltas = new TextField();
		tfDiasFaltas.setCaption("Dias de faltas:");
		tfDiasFaltas.setImmediate(false);
		tfDiasFaltas.setWidth("175px");
		tfDiasFaltas.setHeight("-1px");
		tfDiasFaltas.setSizeFull();
		tfDiasFaltas.setNullRepresentation("");
		gridLayout_1.addComponent(tfDiasFaltas, 0, 6);

		// tfDiasRestantes
		tfDiasRestantes = new TextField();
		tfDiasRestantes.setCaption("Dias restantes:");
		tfDiasRestantes.setImmediate(false);
		tfDiasRestantes.setWidth("175px");
		tfDiasRestantes.setHeight("-1px");
		tfDiasRestantes.setSizeFull();
		tfDiasRestantes.setNullRepresentation("");
		gridLayout_1.addComponent(tfDiasRestantes, 1, 6);

		// pdfDataFim
		pdfDataFim = new PopupDateField();
		pdfDataFim.setCaption("Data término:");
		pdfDataFim.setImmediate(false);
		pdfDataFim.setWidth("175px");
		pdfDataFim.setHeight("-1px");
		gridLayout_1.addComponent(pdfDataFim, 0, 7);

		// cbColaborador
		cbColaborador = new ComboBox();
		cbColaborador.setCaption("Colaborador:");
		cbColaborador.setImmediate(false);
		cbColaborador.setWidth("-1px");
		cbColaborador.setHeight("-1px");
		cbColaborador.setRequired(true);
		gridLayout_1.addComponent(cbColaborador, 1, 7);

		return gridLayout_1;
	}

	/**
	 * COMBOS
	 */

	public void carregarCmbColaborador(List<ColaboradorEntity> lista) {
		BeanItemContainer<ColaboradorEntity> bic = new BeanItemContainer<ColaboradorEntity>(
				ColaboradorEntity.class, lista);
		this.cbColaborador.setContainerDataSource(bic);
		this.cbColaborador.setItemCaptionPropertyId("matricula");
	}

}