package dc.visao.contabilidade.cadastro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.contabilidade.cadastro.IndiceValorFormController;
import dc.entidade.contabilidade.cadastro.IndiceEntity;
import dc.visao.framework.component.manytoonecombo.ManyToOneComboField;
import dc.visao.framework.util.ComponentUtil;

public class IndiceValorFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private PopupDateField pdfDataIndice;

	@AutoGenerated
	private TextField tfValor;

	@AutoGenerated
	private ManyToOneComboField<IndiceEntity> cbIndice;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private IndiceValorFormController controller;

	public IndiceValorFormView(final IndiceValorFormController controller) {
		this.controller = controller;

		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}

	public PopupDateField getPdfDataIndice() {
		return pdfDataIndice;
	}

	public void setPdfDataIndice(PopupDateField pdfDataIndice) {
		this.pdfDataIndice = pdfDataIndice;
	}

	public TextField getTfValor() {
		return tfValor;
	}

	public void setTfValor(TextField tfValor) {
		this.tfValor = tfValor;
	}

	public ManyToOneComboField<IndiceEntity> getCbIndice() {
		return cbIndice;
	}

	public void setCbIndice(ManyToOneComboField<IndiceEntity> cbIndice) {
		this.cbIndice = cbIndice;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_2.addComponent(gridLayout_1);

		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		// gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setRows(4);
		gridLayout_1.setColumns(4);
		
		// cbIndice
		cbIndice = new ManyToOneComboField<>(IndiceEntity.class);
		cbIndice.setCaption("Índice:");
		gridLayout_1.addComponent(cbIndice, 0, 0);

		// pdfDataIndice
		pdfDataIndice = ComponentUtil.buildPopupDateField("Data do índice:");
		gridLayout_1.addComponent(pdfDataIndice, 0, 1, 1,1);

		// tfValor
		//tfValor = new TextField();
		//tfValor.setCaption("Valor:");
		tfValor = ComponentUtil.buildTextField("Valor");
		gridLayout_1.addComponent(tfValor, 2, 1, 3,1);

		return gridLayout_1;
	}

}